site_name: My Site
site_url: https://marco-christiani.github.io/

theme:
  name: material
  features:
    - header.autohide # hide header on scroll
    # - navigation.sections # uncomment to NOT fold left side children
    # - navigation.tabs
    - navigation.indexes 
    - search
    - search.highlight # highlight search occurences
    - search.suggest # autocomplete search terms
    - navigation.tracking # update link on scroll
    - toc.integrate # toc on left, not right
    - navigation.expand


  palette: 
    - scheme: slate # Palette toggle for dark mode
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default # Palette toggle for light mode
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
nav:
  - Home: index.md
  # - "<p>LinkedIn &nbsp<i class='fa-solid fa-arrow-up-right-from-square'></i></p>": foo
  - Topic Cheatsheet: https://marco-christiani.github.io/interview-cheatsheet/
    # - Neural Networks: ml/ann.md
    # - Datasets: ml/data.md
    # - Evaluation: ml/evaluation.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  # Syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets # transclusions
  - pymdownx.superfences # rescursive embeddings?

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css

plugins:
  - blogging:
      dirs: # The directories to be included
        - articles
